FROM ubuntu:14.04
RUN apt-get update && apt-get install -y software-properties-common && add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl -y
RUN apt-get update && apt-get install -y libpcl-all 
