FROM ubuntu:latest

#      libvtk6-dev \
#      libvtk6-qt-dev \
RUN apt-get update && apt-get install -y \
      libboost1.58-all-dev \
      libflann-dev \
      libeigen3-dev \
      cmake \
      libproj-dev \
      libgtk2.0-dev \
      python-dev \
      python-numpy \
      libtbb2 \
      libtbb-dev \
      libdc1394-22-dev
